# Generated by Django 4.0.2 on 2022-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('limited', 'Limited (< 10 )')], default='No', max_length=20),
        ),
    ]
