# Generated by Django 4.0.2 on 2022-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Not-started', 'Not-Started'), ('Obgoing', 'Ongoing'), ('Completed', 'Completed')], default='Not-started', help_text='Status of task', max_length=20),
        ),
    ]
